import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import './globals.css';
import './theme-config.css';
import Provider from './Provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <title>Issue Tracker</title>
      </head>
      <body className={inter.variable}>
        <Provider>
          <Theme accentColor='green' grayColor='sage' scaling='105%'>
            <NavBar />
            <main className='p-5'>{children}</main>
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
